[plugin]
name = "haproxy-discover"
description = "HAProxy Backend Discovery"
version = "0.1.0"
maintainer_name = "Mathias Kaufmann"
maintainer_email = "mathias.kaufmann@kiwigrid.com"
website_url = "http://git.kiwigrid.com/infrastructure/plugn/discover"

[plugin.config]
backend_naming_script = "Script to build backend from container id."
haproxy_config_path   = "Path to haproxy config directory"
reload_script         = "Reload Script of HAProxy"

[plugin.compatibility]
